version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: myapp
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - /var/www/vendor
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  composer:
    image: composer:2.4.0
    entrypoint: "composer"
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app

  nginx:
    image: nginx:1.19-alpine
    container_name: myapp_nginx
    restart: always
    ports:
      # map port 3000 to the internal container port 80
      - "3000:80"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - db
      - phpmyadmin
  db:
    container_name: mysql-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
